### ISSUE TITLE
Bug - Duplicate Logic Error in run_weaving_talkturn.py

### ISSUE THREAD

**Issue by joshkyh** [SpectData/MONAH#21]
The function run_weaving_talkturn in execute_weaveing_talkturn.py is the process that converts word_transcripts.csv into weave talkturns.csv produces a duplicate row as per screen shot. This causes a downstream problem in word_pitch_vol.py line 212 of dev-pitch branch.

![image](https://user-images.githubusercontent.com/14764966/107454465-32231a00-6ba1-11eb-86c3-76a9d32b152e.png)

![image](https://user-images.githubusercontent.com/14764966/107456933-3d784480-6ba5-11eb-9abd-8a63946d0b87.png)

The video pair from Ses01F_impro01_F.

Could we also take this opportunity to improve the commenting detail of run_weaving_talkturn? :)

**Comment by mfmakahiya** [comment]
Hi Joshua! As I was examining the error, I realized this might be specific for iemocap split videos only because of the quality of audio recordings that we have (wherein the other speaker is being heard in the other speaker's recording). So this is actually not just one instance but multiple times in the entire weaved talkturn result. I'm afraid there is no workaround for this instance and the only possible solution I can suggest is using two new examples wherein the other speakers are not heard from each other's recording.

**Comment by joshkyh** [comment]
Hi Marriane, if the other speaker is heard on the speaker file, then I think the same words would have different speakers. However, we see that in the screenshot, the duplicate happened under the same speaker (man). Could you have a look please? :)

**Comment by mfmakahiya** [comment]
![image](https://user-images.githubusercontent.com/44262531/108731856-f2c4d800-7567-11eb-9ff0-52d6db767fd4.png)
Hi Joshua! I can't seem to replicate the same results you got from the above. I'm only getting these results despite running it several times. Talkturn numbers 118 and 119 seem very close to each other but they are recorded from different speakers unlike the above. I didn't edit anything from the script yet so I'm not sure what's actually going on.

I tried to check the other talkturns as well and indeed the other speaker can be heard in the other recording. As a result, we have duplicate talkturns but from different speakers. In quick glance, I didn't notice any duplicate talkturns coming from the same speaker.

**Comment by joshkyh** [comment]
Let's park this since you didn't find any duplicates from the same speaker. The duplicates due to audio being heard in two microphones can't be solved.
